spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
