application:
  dataFilePath: data
  dataFileName: tasks.csv
  incorrectAnswersCountToMark:
    0: 5
    1: 4
    2: 3
    default: 2
spring:
  messages:
    basename: i18/messages
    encoding: UTF-8
    fallback-to-system-locale: false


