CREATE TABLE IF NOT EXISTS AUTHOR
(
    ID BIGINT AUTO_INCREMENT
    PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS GENRE
(
    ID BIGINT AUTO_INCREMENT
    PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS  BOOK
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    ISBN VARCHAR(50) NOT NULL,
    ISSUE_YEAR SMALLINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL
);

ALTER TABLE BOOK ADD CONSTRAINT BOOK_AUTHOR_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON DELETE NO ACTION;

CREATE TABLE IF NOT EXISTS BOOK_GENRE
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID INTEGER NOT NULL CONSTRAINT BOOK_ID_FK REFERENCES BOOK ON DELETE CASCADE,
    GENRE_ID INTEGER NOT NULL CONSTRAINT GENRE_ID_FK REFERENCES GENRE ON DELETE NO ACTION
);


